framework:
    messenger:
        default_bus: event.bus
        buses:
            command.bus: ~
            event.bus:
                middleware:
                    - doctrine_transaction

        transports:
            outbound:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: ticketing
                        type: direct
                    queues: false

            inbound:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: true
                    exchange:
                        name: ticketing
                        type: direct
                    queues:
                        booking.queue:
                            binding_keys:
                                - reservation.confirmed
                                - reservation.cancelled

        routing:
            Ticketing\Contracts\Event\ReservationRequested: outbound
